/**
 * The demo.
 *
 * Fetches each delivery variant the way an LLM crawler does: one plain HTTP
 * request, read the response body, no JavaScript, no subresources, no iframes
 * followed. Then it checks the body for the figures a reader would want to
 * quote, and reports what survived.
 *
 * Run: node build.mjs && node scripts/crawler-view.mjs
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { createServer, listen } from './serve.mjs';

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

/** What an AI answer about this report would need to cite. */
export const PROBES = [
  { label: 'Black Friday email sends', needle: '1,390,289,396' },
  { label: 'Black Friday SMS sends', needle: '5,430,859' },
  { label: 'Gross revenue, email', needle: '$1,132,707,426.53' },
  { label: 'Gross revenue, SMS', needle: '$8,219,537.10' },
  { label: 'Chart axis labels', needle: '1.5B' },
  { label: 'Plain-text takeaway', needle: 'peaked at' },
  { label: 'JSON-LD Dataset', needle: 'application/ld+json' },
  { label: 'Mid-window daily figure', needle: '1,013,302,698' },
];

const VARIANTS = [{ name: 'Client-rendered by React + D3', path: '/index.html' }];

// GPTBot's real user agent string, so the request is honest about what it is.
const USER_AGENT =
  'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; GPTBot/1.2; +https://openai.com/gptbot';

export async function crawl(root = DIST) {
  const server = createServer(root);
  const base = await listen(server);
  const results = [];

  try {
    for (const variant of VARIANTS) {
      const response = await fetch(base + variant.path, {
        headers: { 'user-agent': USER_AGENT },
      });
      const body = await response.text();

      results.push({
        ...variant,
        bytes: body.length,
        probes: PROBES.map((probe) => ({ ...probe, found: body.includes(probe.needle) })),
      });
    }
  } finally {
    server.close();
  }

  return results;
}

export function score(result) {
  return result.probes.filter((probe) => probe.found).length;
}

function report(rows) {
  const width = Math.max(...PROBES.map((probe) => probe.label.length));

  console.log('\nFetched with no JavaScript, as GPTBot / ClaudeBot / PerplexityBot would.\n');

  for (const row of rows) {
    console.log(`${row.name}  (${row.bytes.toLocaleString()} bytes)`);
    for (const probe of row.probes) {
      console.log(
        `  ${probe.found ? 'found  ' : 'MISSING'}  ${probe.label.padEnd(width)}  ${probe.needle}`,
      );
    }
    console.log(`  ${score(row)} of ${PROBES.length} present\n`);
  }

  console.log(
    rows.map((row) => `"${row.name}" exposes ${score(row)} of ${PROBES.length}`).join(', ') + '.\n',
  );
}

function reportHtml(rows) {
  const cells = (row) =>
    row.probes
      .map(
        (probe) =>
          `<td class="matrix__cell matrix__cell--${probe.found ? 'yes' : 'no'}">${probe.found ? 'Found' : 'Missing'}</td>`,
      )
      .join('');

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Crawler view | Holiday Lookback interactive elements</title>
    <link rel="stylesheet" href="tokens.css" />
    <link rel="stylesheet" href="demo.css" />
  </head>
  <body>
    <main class="page">
      <header class="article__header">
        <p class="article__eyebrow">Evidence</p>
        <h1 class="article__heading">What a crawler actually receives</h1>
      </header>
      <p class="article__body">
        Each variant below was fetched with a single HTTP request and no JavaScript, which is how
        GPTBot, ClaudeBot, and PerplexityBot read a page. Generated by
        <code>node scripts/crawler-view.mjs</code> on ${new Date().toISOString().slice(0, 10)}.
      </p>
      <table class="matrix">
        <thead>
          <tr>
            <th scope="col">Delivery</th>
            ${PROBES.map((probe) => `<th scope="col">${probe.label}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${rows
            .map(
              (row) =>
                `<tr><th scope="row">${row.name}<span class="matrix__agent">${row.bytes.toLocaleString()} bytes</span></th>${cells(row)}</tr>`,
            )
            .join('')}
        </tbody>
      </table>
      <p class="article__body"><a href="compare.html">Back to the comparison</a></p>
    </main>
  </body>
</html>
`;
}

const isDirectRun = process.argv[1] === fileURLToPath(import.meta.url);

if (isDirectRun) {
  const results = await crawl();
  report(results);
  writeFileSync(join(DIST, 'crawler-report.html'), reportHtml(results));
}
